### ISSUE TITLE
Dúvida sobre tipo primitivo number

### ISSUE THREAD

**Issue by Lara-Capila** [glaucia86/curso-typescript-zero-to-hero#1]
Olá Gláucia, tudo bem?

Primeiramente gostaria de agradecer pelo curso, conteúdo completo e você explica muito bem! Estou com uma dúvida em relação ao tipo number, no vídeo número 12 você aborda sobre esse tipo e faz alguns exemplos utilizando números hexadecimais, octais e binário mas no console não era impresso o que você usou nos exemplos.

Exemplo: 
`const number4: number = 0b110001;` e o no console imprimia `49`

queria entender esse comportamento, por que ele converte os números para inteiros?

**Comment by glaucia86** [comment]
Porque o computador automaticamente vai interpretar que isso é um número 49!
0b110001 (hexadecimal) === 49!

**Comment by gabe-cabral** [comment]
E porque você declarou o tipo da variável como `number`, então ele vai fazer um _cast_ do valor hexadecimal em número.
Acho que não existe, mas se houvesse um tipo `hex` por exemplo, o resultado poderia ser o inverso:

`const hexadecimal:hex = 49;  // 0b110001`
