### ISSUE TITLE
Missing Primite Type - Symbol

### ISSUE THREAD

**Issue by gleisonkz** [glaucia86/curso-typescript-zero-to-hero#2]
Olá Glaucia tudo bem?

estava dando uma olhada na ementa e vi que no modulo 2 na parte dos tipos básico não possue referencia ao primitivo symbol.

ele não deveria fazer parte deste modulo? pois tmb é suportado pelo typescript.

https://www.typescriptlang.org/docs/handbook/symbols.html

**Comment by glaucia86** [comment]
Puxa! É verdade! Vou ver se comento sobre ele numa parte q inclua sobre classes. Pois fica mais fácil de explicar sobre ele! Obrigada pela dica!

**Comment by leticia-silva-tc** [comment]
Olá, Glaucia!
Primeiramente obrigada por esta utilidade pública 😊

Uma dúvida, este curso compreende os Utility Types?

**Comment by glaucia86** [comment]
@leticia-silva-tc alguns. Mas, não todos!
