### ISSUE TITLE
Configuração do compilador 

### ISSUE THREAD

**Issue by pedrojunior079** [glaucia86/curso-typescript-zero-to-hero#3]
ts-node' n�o � reconhecido como um comando interno
ou externo, um programa oper�vel ou um arquivo em lotes.

[Done] exited with code=1 in 0.067 seconds

**Comment by DIEGOHORVATTI** [comment]
https://github.com/glaucia86/curso-typescript-zero-to-hero/issues/6

**Comment by DIEGOHORVATTI** [comment]
https://github.com/glaucia86/curso-typescript-zero-to-hero/issues/6
