### ISSUE TITLE
5.4 - Uso dos Getters & Setters / Demo 5.4

### ISSUE THREAD

**Issue by rnvdeveloper** [glaucia86/curso-typescript-zero-to-hero#8]
Olá Gláucia. Estou agora terminando a aula 57 do curso e apesar de ter visto aqui no github que o código está correto, no exemplo 04: Set/Get da aula 57 a alteração de dados de 'Sistema da Informação' para 'Análise e Desenvolvimento de Sistemas' não está sendo feita pelo método set cursoS.
Como o video já está gravado, imagino que possa ser interessante colocar uma nota escrita somente.

De já agradeço pelo conteúdo disponibilizado.

**Comment by glaucia86** [comment]
Blz. Farei a nota no vídeo!
